name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    strategy:
      fail-fast: false
      matrix:
        python-version: [2.7, 3.9]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: sudo apt-get install libboost-thread-dev libboost-system-dev libboost-python-dev libboost-python3-dev libv8-dev
      - run: pip install --upgrade pip
      - run: pip install codespell flake8 isort pytest pyupgrade
      - if: matrix.python-version >= 3.6
        run: |
          pip install bandit black
          bandit -r . || true
          black --check . || true
      - run: codespell --quiet-level=2 || true  # --ignore-words-list="" --skip=""
      - run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true
      - run: isort --profile black . || true
      - run: pip install -r requirements.txt
      - run: pytest . || true
      - run: pytest --doctest-modules . || true
      - run: shopt -s globstar && pyupgrade --py36-plus **/*.py || true
